TEST: nice changes

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,12 +1,37 @@
 #!/bin/bash
 source .githooks/helperScripts/fileChecks.sh
+commitAbortionFlag="n"
 # ------------------- Check for white-space error -------------------- #
+
+# Check if this is the initial commit
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+    echo "[pre-commit]: About to create a new commit..................................."
+    against=HEAD
+else
+    echo "[pre-commit]: About to create the first commit..............................."
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
+
+# Use git diff-index to check for whitespace errors
+
+echo "[pre-commit]: Testing for whitespace errors.................................."
+
+if ! git diff-index --check --cached $against
+then
+    echo "[pre-commit]: commit [ABORTED] due to whitespace errors >---------> [FAILURE]"
+    exit 1
+else
+    echo "[pre-commit]: No whitespace errors >---------------------------> [SUCCESSFUL]"
+    # exit 0
+fi
 
 pwd
 .githooks/helperScripts/fileChecks.sh;
 echo "pre-commit TOTAL_WARNINGS_COUNT = " $TOTAL_WARNINGS_COUNT
 if [[ $TOTAL_WARNINGS_COUNT != 0 ]];
 then
+
     echo 'THERE ARE FILE SCAN WARNINGS PRESENT. DO YOU WISH TO ABORT THE COMMIT? (Y/N):\n'
     read commitAbortionFlag
     if [[ ${commitAbortionFlag} == "y"  ||  ${commitAbortionFlag} == "yes" ]];
