TEST: changes in pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,6 @@
 #!/bin/bash
-
+source .githooks/helperScripts/fileChecks.sh
+commitAbortionFlag="n"
 # ------------------- Check for white-space error -------------------- #
 
 # Check if this is the initial commit
@@ -26,5 +27,20 @@ else
 fi
 
 pwd
-cd ..
-/helperScripts/fileChecks.sh;
+.githooks/helperScripts/fileChecks.sh;
+echo "pre-commit TOTAL_WARNINGS_COUNT = " $TOTAL_WARNINGS_COUNT
+if [[ $TOTAL_WARNINGS_COUNT != 0 ]];
+then
+    printf 'THERE ARE FILE SCAN WARNINGS PRESENT. DO YOU WISH TO ABORT THE COMMIT? (Y/N):\n'
+    commitAbortionFlag="y"
+    if [ $commitAbortionFlag == "y" ] || [ $commitAbortionFlag == "yes" ];
+    then
+        echo "[ABORTING] Commit ...................."
+        exit 1
+    else
+        echo "Proceeding to commit ................."
+    fi
+else
+    echo 'Wohoo! SUCCESS! No File Scans Warnings Present! :)'
+fi
+
