adding script for white-space error check

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,36 @@
 #!/bin/bash
 
+# ------------------- Check for white-space error -------------------- #
+
+# Check if this is the initial commit
+if git rev-parse --verify HEAD >/dev/null 2>&1
+then
+    echo "pre-commit: About to create a new commit..."
+    against=HEAD
+else
+    echo "pre-commit: About to create the first commit..."
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+fi
+
+# Use git diff-index to check for whitespace errors
+echo "pre-commit: Testing for whitespace errors..."
+if ! git diff-index --check --cached $against
+then
+    echo "pre-commit: Aborting commit due to whitespace errors"
+    exit 1
+else
+    echo "pre-commit: No whitespace errors :)"
+    exit 0
+fi
+
+# ------------------- Compile Maven Project -------------------- #
+
 #changes directory to glide-template and runs mvn clean verify
 
 CWD=`pwd`
 
 # Get the path of the files which are getting modified
+# need to write code
 
 # Move to the project directory which you want to compile
 
