TEST: sytanx correction and introducing constant for MIN_COMMIT_LENGTH - DEF1289

diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -29,6 +29,15 @@ CURRENT_BRANCH=${arr[0]}
 
 PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)"
 COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)
+MIN_COMMIT_LENGTH=5
+
+if [[ ${#COMMIT_MESSAGE} < $MIN_COMMIT_LENGTH ]]
+then
+    echo 'Commit message is too short..... Commit --------------------------> [ABORTED]'
+    exit 1;
+fi
+
+
 if [[ $CURRENT_BRANCH =~ $PREFIX_REGEX ]]
 then
     TICKET="${BASH_REMATCH[0]}"
