Def1289 rohit (#6)
* TEST: making conditional changes in prepare-commit-msg

* TEST: added additional logs - DEF1289

* TEST: DEF1289 added additional logs

* TEST: removed useless else block - DEF1289

* TEST:  - DEF1289

* TEST: sytanx correction and introducing constant for MIN_COMMIT_LENGTH - DEF1289

diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -18,43 +18,60 @@ elif [[ $CURRENT_BRANCH == *"-"* ]]
 then
     #echo "branch name cotains hyphen"
     separator="-"
-else
-    separator=""
 fi
 
 arr=(${CURRENT_BRANCH//${separator}/ })
 CURRENT_BRANCH=${arr[0]}
 
-echo "CURRENT_BRANCH = "${CURRENT_BRANCH} #
+# echo "CURRENT_BRANCH = "${CURRENT_BRANCH} #
 
 # PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)(_*).*"
 
 PREFIX_REGEX="((DEF|BAK|STRY|MAINT|def|bak|stry|maint|TNTC)[0-9]*)"
 COMMIT_MESSAGE=$(cat $COMMIT_MSG_FILE)
+MIN_COMMIT_LENGTH=5
+
+if [[ ${#COMMIT_MESSAGE} < $MIN_COMMIT_LENGTH ]]
+then
+    echo 'Commit message is too short..... Commit --------------------------> [ABORTED]'
+    exit 1;
+fi
+
+
 if [[ $CURRENT_BRANCH =~ $PREFIX_REGEX ]]
 then
     TICKET="${BASH_REMATCH[0]}"
     # echo "TICKET IS = "${TICKET}
     
-    if [[ $COMMIT_MESSAGE =~ $TICKET ]]
+    if [[ ! $COMMIT_MESSAGE =~ $TICKET ]]
     then
-        exit 0;
-    fi
+        echo "Ticket '${TICKET}', matched in current branch name, appended to commit message."
 
-    echo "Ticket '${TICKET}', matched in current branch name, appended to commit message."
-
-    if [[ $COMMIT_MESSAGE == "TEST"* ]] || [[ $COMMIT_MESSAGE == "test"* ]] || [[ $COMMIT_MESSAGE == "MAINT"* ]] || [[ $COMMIT_MESSAGE == "maint"* ]]
-    then
-        echo ${COMMIT_MESSAGE}" - "${TICKET} > $COMMIT_MSG_FILE
+        if [[ $COMMIT_MESSAGE == "TEST"* ]] || [[ $COMMIT_MESSAGE == "test"* ]] || [[ $COMMIT_MESSAGE == "MAINT"* ]] || [[ $COMMIT_MESSAGE == "maint"* ]]
+        then
+            echo ${COMMIT_MESSAGE}" - "${TICKET} > $COMMIT_MSG_FILE
+            echo "Ticket '${TICKET}', was appended to the commit message!......................"
+            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
+        else
+            echo "TEST: ${COMMIT_MESSAGE} - ${TICKET}" > $COMMIT_MSG_FILE
+            echo "TEST: was pre-fixed to the commit message...................................."
+            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
+        fi
     else
-        echo "TEST: ${COMMIT_MESSAGE} - ${TICKET}" > $COMMIT_MSG_FILE
-        echo "TEST: was pre-fixed to the commit message"
+        if [[ $COMMIT_MESSAGE != "TEST"* ]] && [[ $COMMIT_MESSAGE != "test"* ]] && [[ $COMMIT_MESSAGE != "MAINT"* ]] && [[ $COMMIT_MESSAGE != "maint"* ]]
+        then
+            echo "TEST: ${COMMIT_MESSAGE}" > $COMMIT_MSG_FILE
+            echo "TEST: was pre-fixed to the commit message...................................."
+            echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
+        fi
     fi
 
 elif [[ $COMMIT_MESSAGE == "MAINT"* ]] || [[ $COMMIT_MESSAGE == "TEST"* ]] || [[ $COMMIT_MESSAGE == "test"* ]] || [[ $COMMIT_MESSAGE == "maint"* ]]
 then
+    echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
     exit 0;
 else
     echo "TEST: "${COMMIT_MESSAGE} > $COMMIT_MSG_FILE
-    echo "TEST: was pre-fixed to the commit message"
+    echo "TEST: was pre-fixed to the commit message...................................."
+    echo "Commit Status >------------------------------------------------> [SUCCESSFUL]"
 fi
