Update Simple.yml

diff --git a/.github/workflows/Simple.yml b/.github/workflows/Simple.yml
--- a/.github/workflows/Simple.yml
+++ b/.github/workflows/Simple.yml
@@ -13,8 +13,8 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v2.7.0
         
-#       - name: Try to Fail
-#         run: exit 1
+      - name: Try to Fail
+        run: exit 1
       
       - name: Setup JDK 11 for Sonar Cloud
         uses: actions/setup-java@v1.4.4
@@ -24,7 +24,8 @@ jobs:
       - name: Maven Build
         run: mvn clean install -DskipTests=true
       
-
+      - name: Run JUnit Tests
+        run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
         
   test:
       name: Test
@@ -33,11 +34,35 @@ jobs:
       steps:
         - name: Checkout Code
           uses: actions/checkout@v2.7.0
-          
+
+#         - name: Try to Fail
+#           run: exit 1
+
         - name: Setup JDK 11 for Sonar Cloud
           uses: actions/setup-java@v1.4.4
           with:
               java-version: 11
-              
+
         - name: Run JUnit Tests
           run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
+          
+  deploy:
+      needs: test
+      name: deploy
+      runs-on: ubuntu-latest
+      steps:     
+        - name: Custom Change
+          uses: ServiceNow/servicenow-devops-change@v1.35.2
+          with:
+            devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
+            devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
+            instance-url: ${{ secrets.SN_INSTANCE_URL }}
+            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
+            context-github: ${{ toJSON(github) }}
+            job-name: 'Deploy'
+            change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018"}}'
+            interval: '100'
+            timeout: '3600'
+
+        - name: Run deployment scripts
+          run: echo Completed Deployment.
